# Generated by Django 6.1 on 2026-08-18 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetables & Crops')], max_length=20)),
                ('emoji', models.CharField(blank=True, help_text='Visual aid only — the crop name is always displayed alongside it.', max_length=16)),
                ('growing_duration_days', models.PositiveIntegerField(help_text='Indicative days from planting to the start of the harvest window.')),
                ('harvest_window_days', models.PositiveIntegerField(help_text='Indicative length of the harvest window in days.')),
                ('description', models.TextField(blank=True)),
                ('search_terms', models.JSONField(blank=True, default=list, help_text='Local/alternate names used for searching.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CropIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('growing_notes', models.JSONField(default=list)),
                ('care_guidance', models.JSONField(default=list)),
                ('harvest_guidance', models.TextField(blank=True)),
                ('important_factors', models.JSONField(default=list)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='plants.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop intelligence',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional farmer label, e.g. 'North Row'.", max_length=120)),
                ('planting_date', models.DateField()),
                ('expected_harvest_start', models.DateField()),
                ('expected_harvest_end', models.DateField()),
                ('status', models.CharField(choices=[('GROWING', 'Growing'), ('READY_FOR_HARVEST', 'Ready for harvest'), ('HARVESTED', 'Harvested'), ('ARCHIVED', 'Archived')], default='GROWING', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plants.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', '-created_at'], name='plants_plan_farmer__6a0a14_idx')],
            },
        ),
    ]
