# Generated by Django 6.1 on 2026-08-19 09:33

import django.db.models.deletion
import django.utils.timezone
import plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_seed_crop_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('plant_age_days', models.PositiveIntegerField()),
                ('plant_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('growth_condition', models.CharField(choices=[('faster_than_expected', 'Faster than expected'), ('as_expected', 'About as expected'), ('slower_than_expected', 'Slower than expected'), ('stunted', 'Stunted / barely growing')], max_length=32)),
                ('health_condition', models.CharField(choices=[('healthy', 'Healthy'), ('slightly_unhealthy', 'Slightly unhealthy'), ('unhealthy', 'Unhealthy')], max_length=32)),
                ('leaf_condition', models.CharField(choices=[('healthy', 'Healthy green leaves'), ('slight_yellowing', 'Slight yellowing'), ('yellowing', 'Noticeable yellowing'), ('spots', 'Spots or lesions'), ('wilting', 'Wilting or drooping'), ('damaged', 'Visible damage / holes')], max_length=32)),
                ('flowering_status', models.CharField(blank=True, choices=[('not_flowering', 'Not flowering'), ('starting', 'Starting to flower'), ('flowering', 'Flowering'), ('finished', 'Flowering finished')], max_length=32)),
                ('fruiting_status', models.CharField(blank=True, choices=[('not_fruiting', 'Not fruiting'), ('forming', 'Fruit forming'), ('developing', 'Fruit developing'), ('ripening', 'Fruit ripening')], max_length=32)),
                ('watering_frequency', models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('twice_weekly', 'Twice a week'), ('weekly', 'Weekly'), ('rain_fed', 'Rain-fed only')], max_length=32)),
                ('soil_moisture', models.CharField(blank=True, choices=[('dry', 'Dry'), ('slightly_dry', 'Slightly dry'), ('moist', 'Moist'), ('wet', 'Wet'), ('waterlogged', 'Waterlogged')], max_length=32)),
                ('pest_observation', models.TextField(blank=True)),
                ('disease_observation', models.TextField(blank=True)),
                ('environmental_observations', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to=plants.models.evidence_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='plants.plant')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('reality_vs_expectation', models.JSONField(blank=True, default=dict)),
                ('visual_observations', models.JSONField(blank=True, default=list)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('possible_causes', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('monitoring_advice', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('next_assessment_days', models.PositiveIntegerField(blank=True, null=True)),
                ('image_analyzed', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='plants.assessment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['plant', '-assessment_date'], name='plants_asse_plant_i_5e4d03_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('plant', 'assessment_date'), name='unique_plant_assessment_per_day'),
        ),
    ]
