# Generated by Django 6.1 on 2026-08-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_assessment_riskassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='evidence_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='evidence_validation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
