# Generated by Django 6.1 on 2026-08-25 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_assessment_evidence_validated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy'), ('clay', 'Clay'), ('sandy', 'Sandy'), ('silty', 'Silty'), ('sandy_loam', 'Sandy Loam'), ('clay_loam', 'Clay Loam'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('soil_texture', models.CharField(choices=[('sandy', 'Sandy'), ('loose', 'Loose'), ('fine', 'Fine'), ('sticky', 'Sticky'), ('heavy', 'Heavy'), ('smooth', 'Smooth'), ('grainy', 'Grainy'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('drainage', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('soil_moisture', models.CharField(choices=[('very_dry', 'Very Dry'), ('dry', 'Dry'), ('moderate', 'Moderate'), ('moist', 'Moist'), ('very_wet', 'Very Wet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Null means the Farmer does not know the pH.', max_digits=4, null=True)),
                ('nitrogen', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('phosphorus', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('potassium', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('organic_matter', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Free-text observations, e.g. 'dries out quickly'.")),
                ('language', models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog'), ('ja', 'Japanese')], default='en', max_length=5)),
                ('suitable_fruits', models.JSONField(blank=True, default=list)),
                ('suitable_vegetables', models.JSONField(blank=True, default=list)),
                ('suitable_crops', models.JSONField(blank=True, default=list)),
                ('fertilizer_recommendations', models.JSONField(blank=True, default=list)),
                ('soil_improvement_watering', models.JSONField(blank=True, default=list)),
                ('important_warnings', models.JSONField(blank=True, default=list)),
                ('ai_generated', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
