# Generated by Django 6.1 on 2026-08-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_soilrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilrecommendation',
            name='language',
        ),
    ]
