# Generated by Django 6.1 on 2026-09-18 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_soilrecommendation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='planting_caution_months',
            field=models.JSONField(blank=True, default=list, help_text='Months that are workable but need a named mitigation.'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_caution_note',
            field=models.TextField(blank=True, help_text='Mitigation that makes a caution month workable.'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_months',
            field=models.JSONField(blank=True, default=list, help_text='Month numbers (1-12) when this crop is normally planted here.'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_reason',
            field=models.TextField(blank=True, help_text='Why the preferred window is what it is.'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_risk',
            field=models.TextField(blank=True, help_text='What goes wrong when planted outside the window.'),
        ),
        migrations.CreateModel(
            name='CropVariant',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('growing_duration_days', models.PositiveIntegerField(help_text="Days from planting to the start of this variety's harvest window.")),
                ('harvest_window_days', models.PositiveIntegerField(help_text="Length of this variety's harvest window in days.")),
                ('search_terms', models.JSONField(blank=True, default=list, help_text='Local/alternate names used for searching.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='plants.crop')),
            ],
            options={
                'ordering': ['crop_id', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plants.cropvariant'),
        ),
    ]
