"""
Move soil assessments from categorical answers to soil-detector readings.

WHY THIS IS RENAMES AND NOT DROPS
---------------------------------
The ten assessments recorded before the detector hold real farmer answers,
and each one sits next to an AI recommendation derived from exactly those
answers. Dropping the columns would leave those results unexplained, which
is the one thing the model's own docstring says not to do. So every
categorical column is renamed to `legacy_*` rather than deleted: no data is
touched, and nothing writes to them again.

`ph_level` is the exception that needed no care at all - it was already a
decimal, so it is a plain rename to `soil_ph` and existing values carry
straight over.

The seven genuinely new columns are added nullable. The form requires them
and the serializer enforces that, but the database cannot: the pre-detector
rows have no numeric readings and never will.

Written by hand rather than autogenerated because the autodetector asks
whether each field was renamed or dropped, and getting that wrong silently
destroys the column. The order here matters: every rename runs before the
new column that reuses its name.
"""

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plants", "0009_seed_more_variants")]

    operations = [
        # --- 1. Preserve the categorical answers under legacy_* names ----
        migrations.RenameField("soilrecommendation", "soil_type", "legacy_soil_type"),
        migrations.RenameField(
            "soilrecommendation", "soil_texture", "legacy_soil_texture"
        ),
        migrations.RenameField("soilrecommendation", "drainage", "legacy_drainage"),
        migrations.RenameField(
            "soilrecommendation", "soil_moisture", "legacy_soil_moisture"
        ),
        migrations.RenameField("soilrecommendation", "nitrogen", "legacy_nitrogen"),
        migrations.RenameField("soilrecommendation", "phosphorus", "legacy_phosphorus"),
        migrations.RenameField("soilrecommendation", "potassium", "legacy_potassium"),
        migrations.RenameField(
            "soilrecommendation", "organic_matter", "legacy_organic_matter"
        ),
        # --- 2. pH keeps its values, just under the new name -------------
        migrations.RenameField("soilrecommendation", "ph_level", "soil_ph"),
        migrations.AlterField(
            model_name="soilrecommendation",
            name="soil_ph",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="pH, 3 to 10.",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("3")),
                    django.core.validators.MaxValueValidator(Decimal("10")),
                ],
            ),
        ),
        # --- 3. The readings the detector actually produces ---------------
        migrations.AddField(
            model_name="soilrecommendation",
            name="soil_temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Degrees Celsius, -40 to 80.",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-40")),
                    django.core.validators.MaxValueValidator(Decimal("80")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soilrecommendation",
            name="soil_moisture",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percent, 0 to 100.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soilrecommendation",
            name="soil_conductivity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Microsiemens per centimetre, 0 to 20000.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20000)],
            ),
        ),
        migrations.AddField(
            model_name="soilrecommendation",
            name="nitrogen",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nitrogen in mg/kg, 1 to 1999.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soilrecommendation",
            name="phosphorus",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Phosphorus in mg/kg, 1 to 1999.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soilrecommendation",
            name="potassium",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Potassium in mg/kg, 1 to 1999.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soilrecommendation",
            name="soil_fertility",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Fertility index in mg/kg, 0 to 3000.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(3000)],
            ),
        ),
    ]
