# Generated by Django 6.1 on 2026-09-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_soil_sensor_readings'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='date_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('INCONCLUSIVE', 'Too early to tell')], max_length=16, null=True),
        ),
    ]
