# Generated by Django 6.1 on 2026-09-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_inconclusive_risk_and_date_mismatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropintelligence',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_entries', to='plants.cropvariant'),
        ),
        migrations.AlterField(
            model_name='cropintelligence',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_entries', to='plants.crop'),
        ),
        migrations.AddConstraint(
            model_name='cropintelligence',
            constraint=models.UniqueConstraint(fields=('crop', 'variant'), name='unique_intelligence_per_crop_variant'),
        ),
    ]
