# Generated by Django 6.1 on 2026-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_crop_intelligence_per_variant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cropintelligence',
            name='unique_intelligence_per_crop_variant',
        ),
        migrations.AddField(
            model_name='cropintelligence',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fil', 'Filipino'), ('bik', 'Bikol')], default='en', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='cropintelligence',
            constraint=models.UniqueConstraint(fields=('crop', 'variant', 'language'), name='unique_intelligence_per_crop_variant_language'),
        ),
    ]
