# Generated by Django 6.1 on 2026-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_ai_results_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='leaf_condition',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy green leaves'), ('slight_yellowing', 'Slight yellowing'), ('yellowing', 'Noticeable yellowing'), ('spots', 'Spots or lesions'), ('wilting', 'Wilting or drooping'), ('damaged', 'Visible damage / holes')], max_length=32),
        ),
    ]
