# Generated by Django 6.1 on 2026-10-08 08:08

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Plants already Harvested: the best record of when is their last update."""
    Plant = apps.get_model("plants", "Plant")
    for plant in Plant.objects.filter(status="HARVESTED", harvested_at__isnull=True):
        Plant.objects.filter(pk=plant.pk).update(harvested_at=plant.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_leaf_condition_optional_for_some_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='harvested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
