# Generated by Django 6.1 on 2026-08-19 15:59

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.FarmerManager()),
            ],
        ),
        migrations.CreateModel(
            name='LguOfficer',
            fields=[
            ],
            options={
                'verbose_name': 'LGU Officer',
                'verbose_name_plural': 'LGU Officers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.LguOfficerManager()),
            ],
        ),
    ]
