# Generated by Django 6.1 on 2026-08-19 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ACCOUNT_CREATED', 'Account created'), ('ACCOUNT_APPROVED', 'Account approved'), ('PLANT_ADDED', 'Plant added'), ('PLANT_UPDATED', 'Plant updated'), ('ASSESSMENT_SUBMITTED', 'Assessment submitted'), ('ASSESSMENT_COMPLETED', 'Assessment completed'), ('ASSESSMENT_LOCKED', 'Assessment locked'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('EVIDENCE_ACCEPTED', 'Evidence accepted'), ('EVIDENCE_REJECTED', 'Evidence rejected'), ('AI_EVALUATION_COMPLETED', 'AI evaluation completed'), ('RISK_LOW', 'Low risk'), ('RISK_MEDIUM', 'Medium risk'), ('RISK_HIGH', 'High risk'), ('HARVEST_APPROACHING', 'Harvest approaching'), ('HARVEST_READY', 'Harvest ready'), ('SYSTEM', 'System')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('related_type', models.CharField(blank=True, choices=[('', 'None'), ('plant', 'Plant'), ('assessment', 'Assessment'), ('farmer', 'Farmer')], default='', max_length=32)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=190)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='unique_notification_event_per_recipient')],
            },
        ),
    ]
