# Generated by Django 6.1 on 2026-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account created'), ('ACCOUNT_APPROVED', 'Account approved'), ('PLANT_ADDED', 'Plant added'), ('PLANT_UPDATED', 'Plant updated'), ('ASSESSMENT_SUBMITTED', 'Assessment submitted'), ('ASSESSMENT_COMPLETED', 'Assessment completed'), ('ASSESSMENT_LOCKED', 'Assessment locked'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('EVIDENCE_ACCEPTED', 'Evidence accepted'), ('EVIDENCE_REJECTED', 'Evidence rejected'), ('AI_EVALUATION_COMPLETED', 'AI evaluation completed'), ('RISK_LOW', 'Low risk'), ('RISK_MEDIUM', 'Medium risk'), ('RISK_HIGH', 'High risk'), ('RISK_CHANGED', 'Risk level changed'), ('SOIL_RECOMMENDATION_READY', 'Soil recommendation ready'), ('SOIL_ASSESSMENT_SAVED', 'Soil assessment saved'), ('HARVEST_APPROACHING', 'Harvest approaching'), ('HARVEST_READY', 'Harvest ready'), ('SYSTEM', 'System')], max_length=32),
        ),
    ]
