"""
The Farmer dashboard payload, assembled in one place from MySQL.

WHAT THIS IS FOR
----------------
The dashboard answers three questions — what is happening on my farm, what
needs my attention, and what trends should I know about — and nothing else.
The detail lives on the Plants, Assessments, Soil and Harvest pages, so
nothing here duplicates them.

EVERY FIGURE IS READ, NEVER GUESSED
-----------------------------------
No AI call is involved. The overview sentence is composed from counts this
module has just read out of the database, not generated by a language model:
it is arithmetic, and a model could only make it slower and occasionally
wrong. Where a reading has never been recorded, the payload says so
explicitly rather than sending a zero that would render as a real
measurement.

SOIL READINGS ARE NOT HERE
--------------------------
The detector's eight readings live on the Crop Recommendation page, where
they are entered and where the AI result explains them. The dashboard shows
what came out of that - the crops worth planting - rather than repeating the
raw numbers, which said little on their own.
"""

from __future__ import annotations

from collections import Counter
from datetime import timedelta

from django.utils import timezone

from .assessment_schedule import eligibility
from .models import Assessment, Crop, Plant, SoilRecommendation

# How far back the activity chart looks. Long enough to show a habit
# forming, short enough that a single week still reads clearly.
TREND_DAYS = 30

# A soil reading older than this is treated as stale. Soil chemistry moves
# slowly, so this is about the reading no longer describing the current
# crop cycle rather than about the soil having changed.
SOIL_STALE_DAYS = 90

# Harvests inside this window are called out as imminent.
HARVEST_SOON_DAYS = 14

# Upcoming harvests shown on the dashboard. The Harvest page has them all.
MAX_UPCOMING_HARVESTS = 5

# Suggested crops shown before the card gets too long to scan.
MAX_CROP_SUGGESTIONS = 8


def _plural(count, singular, plural=None):
    return singular if count == 1 else (plural or f"{singular}s")


def assessment_trend(farmer, today=None, days=TREND_DAYS):
    """
    Assessments per day over the trailing window.

    Every day in the range is present, including the zeroes — a line that
    skipped empty days would compress a quiet fortnight into a flat segment
    and misreport how often the farmer is actually assessing.
    """
    today = today or timezone.localdate()
    start = today - timedelta(days=days - 1)

    rows = Assessment.objects.filter(
        plant__farmer=farmer, assessment_date__gte=start, assessment_date__lte=today
    ).values_list("assessment_date", flat=True)

    counts = Counter(rows)
    series = [
        {
            "date": (start + timedelta(days=offset)).isoformat(),
            "count": counts.get(start + timedelta(days=offset), 0),
        }
        for offset in range(days)
    ]
    return {
        "days": series,
        "total": sum(counts.values()),
        "range_days": days,
        "busiest_count": max((d["count"] for d in series), default=0),
    }




def crop_suggestions(farmer, limit=MAX_CROP_SUGGESTIONS):
    """
    Crops the farmer's most recent analysed soil assessment suggested.

    Surfaced on the dashboard because this is the output of the whole
    Crop Recommendation feature and it was otherwise reachable only by
    opening another page - a farmer deciding what to plant next had no
    reason to know it was there.

    Only an analysed assessment is used. A saved-but-unanalysed one has no
    suggestions to show, and an older analysed row would be advice about
    soil the farmer has since re-measured.
    """
    latest = (
        SoilRecommendation.objects.filter(farmer=farmer, ai_generated=True)
        .order_by("-created_at")
        .first()
    )
    if latest is None:
        return {"has_any": False, "recorded_on": None, "crops": []}

    # The three result sections are one list to the farmer: things worth
    # planting. The split into fruit/vegetable/crop matters to the report,
    # not to someone choosing what to put in the ground next.
    crops = []
    for section in ("suitable_fruits", "suitable_vegetables", "suitable_crops"):
        for item in getattr(latest, section) or []:
            name = (item.get("name") or "").strip()
            if not name:
                continue
            crops.append(
                {
                    "id": item.get("id") or "",
                    "name": name,
                    "emoji": item.get("emoji") or "",
                    "reason": (item.get("reason") or "").strip(),
                }
            )
    crops = crops[:limit]

    # Each suggestion carries its planting window, so the card can answer
    # "is this worth planting on the date I picked" without another request.
    # Suiting the soil and being in season are different questions, and a
    # farmer needs both answered before putting something in the ground.
    windows = {
        crop.id: crop
        for crop in Crop.objects.filter(id__in=[c["id"] for c in crops if c["id"]])
    }
    for entry in crops:
        crop = windows.get(entry["id"])
        entry["planting_months"] = list(crop.planting_months or []) if crop else []
        entry["caution_months"] = (
            list(crop.planting_caution_months or []) if crop else []
        )

    return {
        "has_any": bool(crops),
        "recorded_on": latest.created_at.date().isoformat(),
        "crops": crops,
    }


def upcoming_harvests(farmer, today=None, limit=MAX_UPCOMING_HARVESTS):
    """
    The next few harvest windows to open, soonest first.

    Plants already harvested or archived are excluded, and so are windows
    that closed in the past — neither is upcoming.
    """
    today = today or timezone.localdate()
    plants = (
        Plant.objects.filter(farmer=farmer, status__in=["GROWING", "READY_FOR_HARVEST"])
        .filter(expected_harvest_end__gte=today)
        .select_related("crop", "variant")
        .order_by("expected_harvest_start")[:limit]
    )

    return [
        {
            "plant_id": p.id,
            "name": p.display_name,
            "crop_name": p.crop.name,
            "emoji": p.crop.emoji,
            "expected_harvest_start": p.expected_harvest_start.isoformat(),
            "days_away": (p.expected_harvest_start - today).days,
            "in_window": p.expected_harvest_start <= today,
        }
        for p in plants
    ]


def _risk_counts(farmer):
    """Latest risk level per plant. Mirrors the Risk Indicators page."""
    counts = {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "unassessed": 0}
    for plant in Plant.objects.filter(farmer=farmer):
        latest = (
            Assessment.objects.filter(plant=plant)
            .select_related("risk")
            .order_by("-assessment_date", "-created_at")
            .first()
        )
        risk = getattr(latest, "risk", None) if latest else None
        level = risk.risk_level if risk and risk.risk_level else None
        counts[level if level in counts else "unassessed"] += 1
    return counts


def alerts(farmer, today=None):
    """
    What needs the Farmer's attention right now, most urgent first.

    Each entry is derived from a count this function has just read. There is
    no alert that fires on a guess, and an empty list is a real answer — it
    means nothing needs doing, not that the check failed.
    """
    today = today or timezone.localdate()
    out = []

    plants = list(
        Plant.objects.filter(farmer=farmer).select_related("crop", "variant")
    )
    if not plants:
        return out

    counts = _risk_counts(farmer)

    if counts["HIGH"]:
        n = counts["HIGH"]
        out.append(
            {
                "severity": "high",
                "message": (
                    f"{n} {_plural(n, 'plant')} read high risk on "
                    f"{_plural(n, 'its', 'their')} last assessment."
                ),
                "href": "/farmer/risk-indicator",
                "action": "Review",
            }
        )

    if counts["MEDIUM"]:
        n = counts["MEDIUM"]
        out.append(
            {
                "severity": "medium",
                "message": f"{n} {_plural(n, 'plant')} need monitoring after a medium-risk reading.",
                "href": "/farmer/risk-indicator",
                "action": "Review",
            }
        )

    # Harvest windows opening imminently, or already open.
    for h in upcoming_harvests(farmer, today=today, limit=MAX_UPCOMING_HARVESTS):
        if h["in_window"]:
            out.append(
                {
                    "severity": "medium",
                    "message": f"{h['name']} is inside its harvest window now.",
                    "href": "/farmer/harvest",
                    "action": "Open harvest",
                }
            )
        elif h["days_away"] <= HARVEST_SOON_DAYS:
            out.append(
                {
                    "severity": "info",
                    "message": (
                        f"{h['name']} is ready to harvest in {h['days_away']} "
                        f"{_plural(h['days_away'], 'day')}."
                    ),
                    "href": "/farmer/harvest",
                    "action": "Open harvest",
                }
            )

    never_assessed = [p for p in plants if not p.assessments.exists()]
    if never_assessed:
        n = len(never_assessed)
        out.append(
            {
                "severity": "info",
                "message": f"{n} {_plural(n, 'plant')} still {_plural(n, 'needs', 'need')} a first assessment.",
                "href": "/farmer/plants",
                "action": "Assess",
            }
        )

    # Plants off the weekly lock, excluding the ones already counted above.
    due = [
        p
        for p in plants
        if p not in never_assessed and eligibility(p, today)["can_assess"]
    ]
    if due:
        n = len(due)
        out.append(
            {
                "severity": "info",
                "message": f"{n} {_plural(n, 'plant')} {_plural(n, 'is', 'are')} due for a weekly assessment.",
                "href": "/farmer/plants",
                "action": "Assess",
            }
        )

    latest_soil = (
        SoilRecommendation.objects.filter(farmer=farmer).order_by("-created_at").first()
    )
    if latest_soil is None:
        out.append(
            {
                "severity": "info",
                "message": "No soil reading recorded yet.",
                "href": "/farmer/soil-recommendation",
                "action": "Add reading",
            }
        )
    else:
        age = (today - latest_soil.created_at.date()).days
        if age >= SOIL_STALE_DAYS:
            out.append(
                {
                    "severity": "info",
                    "message": f"Your last soil reading was {age} days ago.",
                    "href": "/farmer/soil-recommendation",
                    "action": "Update",
                }
            )

    return out


def overview(farmer, today=None):
    """
    A short factual paragraph describing the farm as it stands.

    Composed from counts, deliberately not from a language model: there is
    nothing here a model could add that arithmetic does not already give
    exactly right, and a model would add latency and a failure mode to a
    sentence that must always render.
    """
    today = today or timezone.localdate()
    counts = _risk_counts(farmer)
    total = sum(counts.values())

    if total == 0:
        return {
            "headline": "No plants yet.",
            "detail": (
                "Add your first plant and BulanTanom will start tracking its "
                "growth, risk and harvest window."
            ),
            "plant_count": 0,
        }

    assessed = counts["LOW"] + counts["MEDIUM"] + counts["HIGH"]
    unassessed = counts["unassessed"]

    parts = []
    if counts["HIGH"]:
        parts.append(f"{counts['HIGH']} reading high risk")
    if counts["MEDIUM"]:
        parts.append(f"{counts['MEDIUM']} medium")
    if counts["LOW"]:
        parts.append(f"{counts['LOW']} low risk")

    if parts and unassessed:
        detail = (
            f"{', '.join(parts)}, and {unassessed} "
            f"{_plural(unassessed, 'crop')} still awaiting a first assessment."
        )
    elif parts:
        detail = f"{', '.join(parts)}."
    else:
        detail = (
            f"{unassessed} {_plural(unassessed, 'crop')} still "
            f"{_plural(unassessed, 'needs', 'need')} a first assessment."
        )

    recent = Assessment.objects.filter(
        plant__farmer=farmer, assessment_date__gte=today - timedelta(days=7)
    ).count()
    if recent:
        detail += f" {recent} {_plural(recent, 'assessment')} submitted in the last 7 days."

    return {
        "headline": (
            f"{total} monitored {_plural(total, 'crop')}, "
            f"{assessed} with a risk reading."
        ),
        "detail": detail,
        "plant_count": total,
    }


def build(farmer, today=None):
    """The whole dashboard payload, in one read."""
    today = today or timezone.localdate()
    return {
        "overview": overview(farmer, today),
        "assessment_trend": assessment_trend(farmer, today),
        "crop_suggestions": crop_suggestions(farmer),
        "upcoming_harvests": upcoming_harvests(farmer, today),
        "alerts": alerts(farmer, today),
    }
